In [1]:
import numpy as np

In [2]:
r = np.random.standard_normal((4, 3))
s = np.random.standard_normal((4, 3))

In [3]:
r + s

array([[-1.83122616, -1.34064484, -1.26932223],
       [ 1.29404698,  1.55063316,  1.71876016],
       [ 0.06669812, -0.69226893,  0.56862351],
       [-1.43118945,  3.82216842, -0.58094726]])

In [4]:
# Memory Layout

x = np.random.standard_normal((5, 10000000))
y = 2 * x + 3 # linear equation
C = np.array((x, y), order='C')
F = np.array((x, y), order='F')
x = 0.0; y = 0.0 # memory cleanup

C[:2].round(2)

array([[[ 0.5 , -1.22, -0.66, ...,  0.75, -0.01, -0.27],
        [-0.62, -0.1 , -0.59, ..., -0.33, -0.35,  1.53],
        [ 1.41,  0.98,  0.28, ..., -0.78,  1.02, -0.09],
        [-2.35, -0.33, -1.26, ...,  0.18, -1.94, -0.62],
        [ 0.86, -0.28,  0.96, ..., -0.85, -0.72, -0.74]],

       [[ 4.01,  0.56,  1.68, ...,  4.49,  2.98,  2.47],
        [ 1.77,  2.8 ,  1.83, ...,  2.35,  2.31,  6.05],
        [ 5.82,  4.97,  3.55, ...,  1.43,  5.03,  2.82],
        [-1.71,  2.34,  0.47, ...,  3.36, -0.89,  1.77],
        [ 4.71,  2.45,  4.92, ...,  1.31,  1.57,  1.52]]])

In [5]:
%timeit C.sum()

42.1 ms ± 581 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
%timeit F.sum()

42 ms ± 394 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
%timeit C[0].sum(axis=0)

76.1 ms ± 698 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
%timeit C[0].sum(axis=1)

21.2 ms ± 264 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
%timeit F[0].sum(axis=0)

117 ms ± 580 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%timeit F[0].sum(axis=1)

96.9 ms ± 956 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
m = np.array([[1,2],[3,4]])
m.sum(axis=0)

array([4, 6])

In [14]:
m.sum(axis=1)

array([3, 7])

In [15]:
C = 0.0; F = 0.0